# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master


pool:
  name: 'Azure Pipelines'


variables:
  solution: '**/MDisasaterDampener.sln'
  project: '**/MDisasaterDampener.csproj'
  tests: '**/MDisasaterDampener.Test..csproj'
  buildConfiguration: 'Release'
steps:
  
- task: NuGetToolInstaller@1
  name: 'NuGetInstaller'
- task: NuGetCommand@2
  name: 'RestoreNuget'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  name: 'UnitTests'
  inputs:
    command: 'test'
    projects: '$(tests)'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
- task: DotNetCoreCLI@2
  name: 'buildArtifact'
  inputs:
    command: 'build'
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  name: 'publishArtifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'mddArtifact'
    publishLocation: 'Container'

